### ISSUE TITLE
RAI, SUSD, TUSD and USDP deposit issues

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#260]
**Blocker for release**

Info from Charlie:

Last night I Deposited RAI.  I deposited 15 RAI which is ~$45 worth, but the swap returned only $5 USDC to the cellar.  It doesn't look like a liquidity issue on Uniswap because when I setup the swap on Uniswap it estimates I would receive the ~$45 USDC
tx link: https://etherscan.io/tx/0x154dbf347be270e80cdd275823ab95659118886497a6139ac30e74fc12923faf

2) Today when I attempted to deposit SUSD I had a couple of failed transactions.  I'm not sure why, but I think the reason may be because the transaction was trying to deposit DAI to the cellar even though I had SUSD selected (you can see it showing "Depositing DAI" in my screenshot below.
tx link: https://etherscan.io/tx/0x0ba9579817c6f1a9f72547eacd68f0e158f8959446102836bde2ed9e00594b61

@luckyOdisetti if you have already a ticket for this one pls link it here

**Comment by warmhyena** [comment]
Update 7.1.22

1. Tried to deposit RAI and the transaction failed (UI showed "Deposit Success": https://etherscan.io/tx/0x060e87a0d4fbb2d0e3dae56e111d9fcbde522dac464012ea4d71615426eba730

2. Same result for USDP: https://etherscan.io/tx/0x293d69d9abe48b6da13279d4acad5262da97773283152e20957d88aba5a1f64b

I am not going to test the rest of the coins right now because it seems like this is the same issue for all, and I am running low on testing funds.

**Comment by henrio123** [comment]
@warmhyena thanks for the update, please request additional testing funds from Stephanie if needed. 

@luckyOdisetti could you take a look at this ticket?

**Comment by henrio123** [comment]
need to retest with final final Cellar Router contract

**Comment by 0xble** [comment]
The issue is that the old `CellarRouter` is being used. As a result, this swap is using the [RAI/USDC Uniswap V3 pool with a 0.3% fee](https://etherscan.io/address/0x209B4654B88437F79165Bb33d1D1f67BD1759784) which has almost no liquidity. Instead it should be using the [RAI/USDC Uniswap V3 pool with a 0.05% fee](https://etherscan.io/address/0xFA7D7A0858a45C1b3b7238522A0C0d123900c118) for the amount swapped.

**Comment by warmhyena** [comment]
Update: RAI, TUSD, SUSD and USDP all deposited to Cellar correctly today.
